/:
  controller: Main
  action: index
  #format: html
  format: application/json

/admin:
  controller: Main
  action: dashboard

/admin/login:
  controller: Security
  action: login

/logout:
  controller: Security
  action: logout

/admin/register:
  controller: Security
  action: register

/admin/confirmation:
  controller: Security
  action: confirmation

/admin/users:
  controller : User
  action : showUsers

/admin/deleteuser:
  controller: User
  action: deleteUsers

/admin/edituser:
  controller: User
  action: setting

/admin/pages:
    controller: Page
    action : listPages

/admin/updatepage:
  controller: Page
  action: updatePage

/showpage:
  controller: Page
  action: showPage

/admin/newpage:
  controller: Page
  action: createPage

/preview:
  controller: Page
  action: publish

/admin/deletepage:
  controller: Page
  action: deletePage

/admin/profil:
  controller: User
  action: home

/admin/signout:
  controller: Security
  action: logout

/error404:
  controller: Error
  action: error404

/{slug}:
  controller : Page
  action : getSlug
/admin/chart:
  controller: ChartController
  action: displayChart


/article/create:
  controller: ArticleController
  action: create

/article/view:
  controller: ArticleController
  action: list

/article/add-comment:
  controller: CommentController
  action: addComment

/article/report-comment:
  controller: CommentController
  action: reportComment


