/:
  controller: Main
  action: index

/dashboard:
  controller: Main
  action: dashboard

/contact:
  controller: Main
  action: contact

/login:
  controller: Security
  action: login

/logout:
  controller: Security
  action: logout

/register:
  controller: Security
  action: register

/:
  controller: Comment
  action: index

/comment/create:
  controller: Comment
  action: create

/comment:
  controller: Comment
  action: store

/comment/{id}/edit:
  controller: Comment
  action: edit

/comment/{id}:
  controller: Comment
  action: update

/comment/{id}/delete:
  controller: Comment
  action: delete