/admin:
  controller: Main
  action: index

/:
  controller: Main
  action: dashboard

/admin/login:
  controller: Security
  action: login

/logout:
  controller: Security
  action: logout
  security: true

/admin/register:
  controller: Security
  action: register

/admin/confirmation:
  controller: Security
  action: confirmation

/admin/users:
  controller : User
  action : showUsers
  security: true

/admin/deleteuser:
  controller: User
  action: deleteUsers
  security: true

/admin/edituser:
  controller: User
  action: setting
  security: true

/admin/theme:
  controller: User
  action: theme
  security: true

/admin/pages:
    controller: Page
    action : listPages
    security: true

/updatepage:
  controller: Page
  action: updatePage
  security: true
  role:
        - 0
        - 1

/showpage:
  controller: Page
  action: showPage

/admin/newpage:
  controller: Page
  action: createPage
  security: true
  role:
    - 0
    - 1

/preview:
  controller: Page
  action: publish

/deletepage:
  controller: Page
  action: deletePage
  security: true
  role:
    - 0

/admin/profil:
  controller: User
  action: home
  security: true

/admin/signout:
  controller: Security
  action: logout
  security: true
  role:
    - 0
    - 1

/admin/sitemap:
  controller: SiteMapGenerator
  action: generate
  security: true

/error404:
  controller: Error
  action: error404

/{slug}:
  controller : Page
  action : getSlug

/installer:
  controller: Installer
  action: start

/admin/front:
  controller: Settings
  action: update
  security: true
  role:
    - 0
    - 1

/admin/menu:
  controller: Settings
  action: updateMenu
  security: true
  role:
    - 0
    - 1