/:
  controller: Main
  action: index

/dashboard:
  controller: Main
  action: dashboard

/contact:
  controller: Main
  action: contact

/login:
  controller: Security
  action: login

/logout:
  controller: Security
  action: logout

/register:
  controller: Security
  action: register

/confirmation:
  controller: Security
  action: confirmation

/users:
  controller : User
  action : showUsers

/deleteuser:
  controller: User
  action: deleteUsers

/pagebuilder:
  controller: Page
  action: newpage

/installer:
  controller: Installer
  action: index
/comment/create:
  controller: Comment
  action: create
/comment:
  controller: Comment
  action: store
/comment/{id}/edit:
  action: edit
  controller: Comment
/comment/{id}:
  controller: Comment
  action: update
/comment/{id}/delete:
  controller: Comment
  action: delete