/:
  controller: Main
  action: index

/admin:
  controller: Main
  action: dashboard

/admin/login:
  controller: Security
  action: login

/logout:
  controller: Security
  action: logout

/register:
  controller: Security
  action: register

/admin/confirmation:
  controller: Security
  action: confirmation

/admin/users:
  controller : User
  action : showUsers

/deleteuser:
  controller: User
  action: deleteUsers

/edituser:
  controller: User
  action: setting

/admin/pages:
    controller: Page
    action : listPages

/updatepage:
  controller: Page
  action: updatePage

/admin/showpage:
  controller: Page
  action: showPage

/admin/newpage:
  controller: Page
  action: createPage

/preview:
  controller: Page
  action: publish

/deletepage:
  controller: Page
  action: deletePage

/admin/profil:
  controller: User
  action: home

/signout:
  controller: Security
  action: logout

/error404:
  controller: Error
  action: error404

/{slug}:
  controller : Page
  action : getSlug

/installer:
  controller: Installer
  action: start