/admin:
  controller: Main
  action: index

/:
  controller: Main
  action: dashboard

/admin/login:
  controller: Security
  action: login

/logout:
  controller: Security
  action: logout

/admin/register:
  controller: Security
  action: register

/admin/confirmation:
  controller: Security
  action: confirmation

/admin/users:
  controller : User
  action : showUsers

/admin/deleteuser:
  controller: User
  action: deleteUsers

/admin/edituser:
  controller: User
  action: setting

/admin/theme:
  controller: User
  action: theme

/admin/pages:
    controller: Page
    action : listPages

/updatepage:
  controller: Page
  action: updatePage

/showpage:
  controller: Page
  action: showPage

/admin/newpage:
  controller: Page
  action: createPage

/preview:
  controller: Page
  action: publish

/deletepage:
  controller: Page
  action: deletePage

/admin/profil:
  controller: User
  action: home

/admin/signout:
  controller: Security
  action: logout

/admin/sitemap:
  controller: SiteMapGenerator
  action: generate

/error404:
  controller: Error
  action: error404

/{slug}:
  controller : Page
  action : getSlug

/installer:
  controller: Installer
  action: start

/admin/front:
  controller: Front
  action: update

/admin/comments:
  controller: Comment
  action: showComments

/admin/comments/update:
  controller: Comment
  action: updateComments

/admin/comments/add:
  controller: Comment
  action: addComment

/admin/comments/delete:
  controller: Comment
  action: deleteComments
