/:
  controller: Main
  action: index

/dashboard:
  controller: Main
  action: dashboard

/contact:
  controller: Main
  action: contact

/login:
  controller: Security
  action: login

/logout:
  controller: Security
  action: logout

/register:
  controller: Security
  action: register

/confirmation:
  controller: Security
  action: confirmation

/users:
  controller : User
  action : showUsers

/deleteuser:
  controller: User
  action: deleteUsers

/pagebuilder:
  controller: Page
  action: newpage

/article/create:
  controller: ArticleController
  action: create

/article/view:
  controller: ArticleController
  action: list

/article/add-comment:
  controller: ArticleController
  action: addComment
